import {useState} from 'react';
import {Link, useNavigate} from 'react-router-dom';
import {useI18n} from '../../i18n/useI18n';
import {api, session, saveSession} from '../../api/client';
import {State, Notice, Field, Badge, DateText, Empty} from '../../components/UI';
import {useResource} from '../../components/useResource';
export default function Profile(){
 const navigate=useNavigate(),{t,setLanguage}=useI18n(),r=useResource('/auth/me'),consents=useResource('/account/consents'),notifications=useResource('/account/notifications'),[message,setMessage]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function save(e){e.preventDefault();setBusy(true);setError('');try{const user=await api('/auth/me',{method:'PATCH',body:Object.fromEntries(new FormData(e.currentTarget))});saveSession({...session(),user});setLanguage(user.preferred_language);setMessage('Profile saved.');}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function consent(c){setBusy(true);setError('');try{await api('/account/consents/'+c.id,{method:'PATCH',body:{status:c.status==='active'?'withdrawn':'active'}});consents.reload();}catch(e){setError(e.message);}finally{setBusy(false);}}
 return <section><h1>{t('Notifications and profile')}</h1><Notice message={message}/><Notice message={error} error/><div className="grid two"><section className="card"><h2>{t('Profile')}</h2><State resource={r}>{u=><form onSubmit={save}><Field label="Full name" name="name" defaultValue={u.name} required minLength={2} maxLength={120}/><Field label="Preferred language" name="preferred_language" defaultValue={u.preferred_language}><option value="en">English</option><option value="hi">हिन्दी</option><option value="or">ଓଡ଼ିଆ</option></Field><Field label="Locality" name="locality" defaultValue={u.locality||''}/><Field label="Ward or village" name="ward_village" defaultValue={u.ward_village||''}/><p>{t(u.role)} · {u.state} · {u.district}</p><button disabled={busy}>{t('Save profile')}</button></form>}</State></section><section className="card"><h2>{t('Notifications')}</h2><State resource={notifications}>{rows=>rows.length?<ul>{rows.map(n=><li key={n.id}><Link to={'/citizen/requests/'+n.need_id}>{t(n.category)}</Link> · <Badge>{n.status}</Badge> <DateText value={n.created_at}/></li>)}</ul>:<Empty/>}</State></section></div><h2>{t('Consent')}</h2><p>{t('Withdrawing account consent stops new reports. Existing records remain for review; evidence stays private.')}</p><State resource={consents}>{rows=>rows.map(c=><article className="card" key={c.id}><h3>{t(c.purpose)}</h3><Badge>{c.status}</Badge><p>{t('Consent version')}: {c.version} · <DateText value={c.recorded_at}/></p><button disabled={busy} onClick={()=>consent(c)}>{t(c.status==='active'?'Withdraw consent':'Give consent again')}</button></article>)}</State>{r.data?.role!=='admin'&&<details className="card"><summary>{t('Erase my account data')}</summary><p>{t('This removes your profile details, report text and media. Anonymous operational records and audit history remain. This cannot be undone.')}</p><form onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);setBusy(true);setError('');try{await api('/account/erase',{method:'POST',body:{password:f.get('password'),confirm:true}});saveSession(null);navigate('/');}catch(e){setError(e.message);}finally{setBusy(false);}}}><Field label="Password" name="password" type="password" required/><label className="check"><input type="checkbox" required/>{t('I understand and confirm erasure.')}</label><button disabled={busy}>{t('Erase my account data')}</button></form></details>}</section>;
}
