import {useState} from 'react';
import {Link} from 'react-router-dom';
import {useI18n} from '../../i18n/useI18n';
import {api} from '../../api/client';
import {State, Empty, Badge, Notice, DateText, Field} from '../../components/UI';
import {useResource} from '../../components/useResource';
export function DataTable({rows}){
 const {t}=useI18n();if(!rows.length)return <Empty/>;
 const keys=Object.keys(rows[0]).filter(k=>!['id','user_id'].includes(k));
 return <div className="table-wrap"><table><thead><tr>{keys.map(k=><th scope="col" key={k}>{t(k)}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={r.id||i}>{keys.map(k=><td key={k}>{r[k]==null?t('Information Not Available'):Array.isArray(r[k])?r[k].map(t).join(', '):k.endsWith('_at')||k==='timestamp'?<DateText value={r[k]}/>:t(String(r[k]))}</td>)}</tr>)}</tbody></table></div>;
}
export function AuditPage(){
 const {t}=useI18n(),[action,setAction]=useState(''),[filter,setFilter]=useState(''),r=useResource('/admin/audit-logs?'+new URLSearchParams({action:filter}));
 return <section><h1>{t('Audit logs')}</h1><p>{t('Read-only history of account and reporting actions.')}</p><Link to="/admin/ai-ops">{t('AI and data operations')}</Link><form className="filter-bar" onSubmit={e=>{e.preventDefault();setFilter(action);}}><Field label="Action filter" value={action} onChange={e=>setAction(e.target.value)}/><button>{t('Filter')}</button></form><State resource={r}>{rows=><DataTable rows={rows}/>}</State></section>;
}
const sections=['overview','users','roles','requests','moderation','data-governance','consent','audit-logs','integrations','health','reports'];
export default function AdminDashboard(){
 const {t}=useI18n(),[section,setSection]=useState('overview'),[status,setStatus]=useState('pending_approval'),[error,setError]=useState(''),[busy,setBusy]=useState(false),[note,setNote]=useState('');
 const path=section==='moderation'?'requests?review=true':section==='users'?'users?'+new URLSearchParams(status?{status}:{}):section;
 const r=useResource('/admin/'+path),applications=useResource(section==='users'?'/admin/access-requests':null);
 async function change(path,body){setBusy(true);setError('');try{await api('/admin/'+path,{method:'PATCH',body});r.reload();applications.reload();}catch(e){setError(e.message);}finally{setBusy(false);}}
 return <section><header className="page-heading"><h1>{t('Administration')}</h1><Link to="/admin/ai-ops">{t('AI and data operations')}</Link></header><div className="split"><nav className="sidebar" aria-label={t('Administration')}>{sections.map(s=><button key={s} className={section===s?'':'secondary'} onClick={()=>setSection(s)} aria-current={section===s?'page':undefined}>{t(s==='health'?'System health':s)}</button>)}</nav><div className="stack"><h2>{t(section==='health'?'System health':section)}</h2><Notice message={error} error/>
 {section==='users'&&<Field label="Status" value={status} onChange={e=>setStatus(e.target.value)}>{['pending_approval','active','suspended','rejected',''].map(s=><option key={s} value={s}>{t(s||'All')}</option>)}</Field>}
 {section==='moderation'&&<Field label="Private review note" value={note} minLength={3} maxLength={1000} onChange={e=>setNote(e.target.value)}/>}
 <State resource={r}>{data=>section==='users'?<>{data.length?data.map(u=><article className="card" key={u.id}><h3>{u.name}</h3><p>{t(u.role)} · {u.state} · {u.district}</p><Badge>{u.status}</Badge>{u.role!=='admin'&&<div className="actions">{(u.status==='pending_approval'?['active','rejected']:u.status==='active'?['suspended']:u.status==='suspended'?['active']:[]).map(s=><button key={s} disabled={busy} onClick={()=>change('users/'+u.id+'/status',{status:s})}>{t(s==='active'?'Approve or restore':s==='rejected'?'Reject':'Suspend')}</button>)}</div>}</article>):<Empty/>}<h3>{t('Access applications')}</h3><State resource={applications}>{rows=><DataTable rows={rows}/>}</State></>:section==='moderation'?data.length?data.map(n=><article className="card" key={n.id}><h3>{t(n.category)} · {n.district}</h3><Link to={"/admin/requests/"+n.id}>{t("Review evidence")}</Link><Badge>{n.moderation_reason||'Requires Review'}</Badge><div className="actions">{['clear_review','reject'].map(action=><button key={action} disabled={busy||note.trim().length<3} onClick={()=>change('requests/'+n.id,{action,note})}>{t(action)}</button>)}</div></article>):<Empty/>:section==='consent'?data.length?data.map(c=><article className="card" key={c.id}><p>{t(c.purpose)} · <Badge>{c.status}</Badge> · <DateText value={c.recorded_at}/></p><small>{c.id}</small>{c.status==='active'&&<button disabled={busy} onClick={()=>change('consent/'+c.id,{status:'withdrawn'})}>{t('Withdraw consent')}</button>}</article>):<Empty/>:section==='requests'?<>{data.map(n=><article className="card" key={n.id}><p>{t(n.category)} · {n.district} · {t(n.status)}</p><Link to={"/admin/requests/"+n.id}>{t("Review evidence")}</Link></article>)}</>:Array.isArray(data)?<DataTable rows={data}/>:<div className="grid two">{Object.entries(data).map(([key,value])=><article className="card" key={key}><h3>{t(key)}</h3>{Array.isArray(value)?<DataTable rows={value}/>:<p>{typeof value==='number'?value:t(value)}</p>}</article>)}</div>}</State></div></div></section>;
}
